### ISSUE TITLE
ERROR : Request failed with status code 401

### ISSUE THREAD

**Issue by Mohamedkhalidh** [sumithemmadi/truecallerjs#34]
Hello .. I would like to thank you for the effort made in this application..
I'm facing a problem that when I search for a number I get this Error , Also when I review my installation ID it shows "Undefined"
Note : I have a premium(Paid) version of truecaller

**Comment by sumithemmadi** [comment]
Which version of truecallerjs

**Comment by RabbitFored** [comment]
`code 401` means you are unauthorized, your installationID might by revoked or expired. 

Can you share your code?

**Comment by sumithemmadi** [comment]
@Mohamedkhalidh  In some older versions of `truecallerjs`, I made a mistake that caused a problem when the fs library tried to read the installation. This mistake led to an error because the installationid wasn't defined properly and was used as if it were an installationId with no value. This problem has been fixed in newer versions of [truecallerjs](https://github.com/sumithemmadi/truecallerjs).
