### ISSUE TITLE
truecallerjs error backup found 

### ISSUE THREAD

**Issue by itzdamnsukhyy** [sumithemmadi/truecallerjs#64]
i'm getting an error after getting an otp it says backup found and not letting me get in can anybody help me please to fix the issue and Thank you in advance for helping me out

**Comment by raknos13** [comment]
Same issue, can't seem to find a solution

**Comment by Pranjul2006** [comment]
please solve the problem of truecallerjs back found error please anybody can solve it

**Comment by syntaxticsugr** [comment]
@sumithemmadi This issue arises because of VerifyOtp respose status 17 which is unaccounted for in your codebase. When the response status is 17, the `installationId` parameter is not included in the returned response.

The solution to this problem is to send a request using the following details:

```
METHOD: POST
URL: "https://account-noneu.truecaller.com/v1/completeOnboarding"
BODY: {
    countryCode: String,
    dialingCode: Int,
    phoneNumber: String,
    requestId: String
}
```
*The `requestId` will be the same from RequestOtp response.

Upon success, the returned response will include `installationId: String` and `suspended: Boolean` parameters.

**Comment by TechLion123432** [comment]
Pls can u help it in detail about the same error

**Comment by RohitChoubey72** [comment]
can u please explain in detail...or the full process of how to fix it...please

**Comment by sumithemmadi** [comment]
#11

**Comment by sumithemmadi** [comment]
Similar to #11

**Comment by Benojir** [comment]
> TechLion123432

Thank you sir
